name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  Tests:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        deno: ['v1.x', 'canary']

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Run tests
        run: deno test --doc src/ffmpegClass.ts && deno test -A --fail-fast tests

  Linting:
    runs-on: 'ubuntu-latest'
    
    strategy:
      matrix:
        deno: ['v1.x', 'canary']

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run Linter
        run: deno lint

  Formatting:
    runs-on: 'ubuntu-latest'
    
    strategy:
      matrix:
        deno: ['v1.x', 'canary']

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run Formatter
        run: deno fmt